export enum Types {
  UPDATE_CATEGORIES = "UPDATE_CATEGORIES",
  UPDATE_FEEDS = "UPDATE_FEEDS",
  SELECT_FEED = "SELECT_FEED",
  UPDATE_ENTRIES = "UPDATE_ENTRIES",
  SELECT_ENTRY = "SELECT_ENTRY",
  SHOW_FEED_DIALOG = "SHOW_FEED_DIALOG",
  HIDE_FEED_DIALOG = "HIDE_FEED_DIALOG"
}